version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"

  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: "increase"
    groups:
      all-npm-version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
